### ISSUE TITLE
uaac recommends the `--skip-ssl-validation` flag, then doesn't understand it

### ISSUE THREAD

**Issue by erjoalgo** [cloudfoundry/cf-uaac#41]
uaac  doesn't understand the `--skip-ssl-validation` it recommends
```bash
$ uaac token client get admin -s adminsecret

CF::UAA::SSLException: Invalid SSL Cert for https://127.0.0.1:8580/login. Use '--skip-ssl-validation' to continue with an insecure target

attempt to get token failed
$ uaac token client get admin -s adminsecret

Invalid option: skip_ssl_validation

  token client get [id]            Gets a token with client credentials grant
                                   -s | --secret <secret>, client secret
                                   --scope <list>

$ uaac --skip-ssl-validation token client get admin -s adminsecret

Invalid option: skip_ssl_validation

  token client get [id]            Gets a token with client credentials grant
                                   -s | --secret <secret>, client secret
                                   --scope <list>

$ uaac token --skip-ssl-validation client get admin -s adminsecret

Invalid option: skip_ssl_validation

  token client get [id]            Gets a token with client credentials grant
                                   -s | --secret <secret>, client secret
                                   --scope <list>

$ uaac token client --skip-ssl-validation get admin -s adminsecret

Invalid option: skip_ssl_validation

  token client get [id]            Gets a token with client credentials grant
                                   -s | --secret <secret>, client secret
                                   --scope <list>

$ uaac token client get --skip-ssl-validation admin -s adminsecret

Invalid option: skip_ssl_validation

  token client get [id]            Gets a token with client credentials grant
                                   -s | --secret <secret>, client secret
                                   --scope <list>

$ uaac token client get admin --skip-ssl-validation -s adminsecret

Invalid option: skip_ssl_validation

  token client get [id]            Gets a token with client credentials grant
                                   -s | --secret <secret>, client secret
                                   --scope <list>

$ uaac token client get admin -s adminsecret --skip-ssl-validation

Invalid option: skip_ssl_validation

  token client get [id]            Gets a token with client credentials grant
                                   -s | --secret <secret>, client secret
                                   --scope <list>

```

UAA client 3.12.0

**Comment by sreetummidi** [comment]
Please perform --skip-ssl-validation at the time of uaac target

**Comment by strehle** [comment]
@bruce-ricard  you re-opened it, so do you see an open issue ?

**Comment by bgandon** [comment]
I remember hitting this caveat, years ago when I wasn't experienced with the `uaac` CLI yet.
So, I've pushed some documentation update in #109.

**Comment by strehle** [comment]
@bgandon  thanks

**Comment by bruce-ricard** [comment]
IMO that's still an issue. But we probably won't ever get to it :)
